In [2]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)


import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

/kaggle/input/tweets_202001121218.csv

In [20]:
!pip install tweet-preprocessor

Requirement already satisfied: tweet-preprocessor in /opt/conda/lib/python3.6/site-packages (0.5.0)

In [21]:
import preprocessor as p

In [22]:
train_df = pd.read_csv('/kaggle/input/tweets_202001121218.csv')

In [26]:
train_df.head()

,id,created_at,query,text,negative,neutral,positive,compound
0,1215995577206550528,"1,578,750,918,462",fortnite,Fortnite players. How tf do you yeet an opppnent,0.000,1.000,0.000,0.0000
1,1215995574367014912,"1,578,750,918,476",fortnite,Highlight against censor. \n.\n\n#gaming #game...,0.085,0.847,0.068,-0.1531
2,1215995566154493952,"1,578,750,918,480",fortnite,Why all these 15 year old Asian guys beefin on...,0.063,0.845,0.091,0.2640
3,1215995562291597313,"1,578,750,918,488",fortnite,*fortnite dances to the iphone 6 ringtone*,0.000,1.000,0.000,0.0000
4,1215995520063344641,"1,578,750,918,493",fortnite,Check out my broadcast from my PlayStation 4! ...,0.000,1.000,0.000,0.0000

In [23]:
train_df.count()

id            182299
created_at    182299
query         182299
text          182299
negative      182299
neutral       182299
positive      182299
compound      182299
dtype: int64

In [ ]:
train_df = train_df.dropna()
train_df = train_df.drop_duplicates()

In [24]:
train_df.count()

id            182299
created_at    182299
query         182299
text          182299
negative      182299
neutral       182299
positive      182299
compound      182299
dtype: int64

In [25]:
train_df.head()

,id,created_at,query,text,negative,neutral,positive,compound
0,1215995577206550528,"1,578,750,918,462",fortnite,Fortnite players. How tf do you yeet an opppnent,0.000,1.000,0.000,0.0000
1,1215995574367014912,"1,578,750,918,476",fortnite,Highlight against censor. \n.\n\n#gaming #game...,0.085,0.847,0.068,-0.1531
2,1215995566154493952,"1,578,750,918,480",fortnite,Why all these 15 year old Asian guys beefin on...,0.063,0.845,0.091,0.2640
3,1215995562291597313,"1,578,750,918,488",fortnite,*fortnite dances to the iphone 6 ringtone*,0.000,1.000,0.000,0.0000
4,1215995520063344641,"1,578,750,918,493",fortnite,Check out my broadcast from my PlayStation 4! ...,0.000,1.000,0.000,0.0000

In [27]:
def preprocess_tweet(row):
    text = row['text']
    text = p.clean(text)
    return text

In [29]:
train_df['text'] = train_df.apply(preprocess_tweet, axis=1)

In [30]:
train_df.head()

,id,created_at,query,text,negative,neutral,positive,compound
0,1215995577206550528,"1,578,750,918,462",fortnite,Fortnite players. How tf do you yeet an opppnent,0.000,1.000,0.000,0.0000
1,1215995574367014912,"1,578,750,918,476",fortnite,Highlight against censor. .,0.085,0.847,0.068,-0.1531
2,1215995566154493952,"1,578,750,918,480",fortnite,Why all these year old Asian guys beefin on th...,0.063,0.845,0.091,0.2640
3,1215995562291597313,"1,578,750,918,488",fortnite,*fortnite dances to the iphone ringtone*,0.000,1.000,0.000,0.0000
4,1215995520063344641,"1,578,750,918,493",fortnite,Check out my broadcast from my PlayStation ! (...,0.000,1.000,0.000,0.0000

In [31]:
from gensim.parsing.preprocessing import remove_stopwords

In [32]:
def stopword_removal(row):
    text = row['text']
    text = remove_stopwords(text)
    return text

In [33]:
train_df['text'] = train_df.apply(stopword_removal, axis=1)

In [34]:
train_df.head()

,id,created_at,query,text,negative,neutral,positive,compound
0,1215995577206550528,"1,578,750,918,462",fortnite,Fortnite players. How tf yeet opppnent,0.000,1.000,0.000,0.0000
1,1215995574367014912,"1,578,750,918,476",fortnite,Highlight censor. .,0.085,0.847,0.068,-0.1531
2,1215995566154493952,"1,578,750,918,480",fortnite,Why year old Asian guys beefin tl? And asking ...,0.063,0.845,0.091,0.2640
3,1215995562291597313,"1,578,750,918,488",fortnite,*fortnite dances iphone ringtone*,0.000,1.000,0.000,0.0000
4,1215995520063344641,"1,578,750,918,493",fortnite,Check broadcast PlayStation ! (Fortnite) live,0.000,1.000,0.000,0.0000

In [35]:
train_df['text'] = train_df['text'].str.lower().str.replace('[^\w\s]',' ').str.replace('\s\s+', ' ')

In [36]:
train_df.head()

,id,created_at,query,text,negative,neutral,positive,compound
0,1215995577206550528,"1,578,750,918,462",fortnite,fortnite players how tf yeet opppnent,0.000,1.000,0.000,0.0000
1,1215995574367014912,"1,578,750,918,476",fortnite,highlight censor,0.085,0.847,0.068,-0.1531
2,1215995566154493952,"1,578,750,918,480",fortnite,why year old asian guys beefin tl and asking a...,0.063,0.845,0.091,0.2640
3,1215995562291597313,"1,578,750,918,488",fortnite,fortnite dances iphone ringtone,0.000,1.000,0.000,0.0000
4,1215995520063344641,"1,578,750,918,493",fortnite,check broadcast playstation fortnite live,0.000,1.000,0.000,0.0000

In [ ]:
train_df.to_csv('f21.csv')